language: generic  

services:
  - docker
sudo: required

before_install:
  - docker build -t rsharma/fibby-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run rsharma/fibby-test yarn run test -- --coverage

after_success:
  # build production images
  - docker build -t rsharma/fibby-client ./client
  - docker build -t rsharma/fibby-nginx ./nginx
  - docker build -t rsharma/fibby-server ./server
  - docker build -t rsharma/fibby-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push production image??????????????????????????????????-client
  - docker push rsharma/fibby-nginx
  - docker push rsharma/fibby-server
  - docker push rsharma/fibby-worker



