language: generic  

services:
  - docker
sudo: required

before_install:
  - docker build -t rsharma/fib-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run rsharma/fib-test yarn run test -- --coverage

after_success:
  # build production images
  - docker build -t rsharma/fib-client ./client
  - docker build -t rsharma/fib-nginx ./nginx
  - docker build -t rsharma/fib-server ./server
  - docker build -t rsharma/fib-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push production images to docker hub
  - docker push rsharma/fib-client
  - docker push rsharma/fib-nginx
  - docker push rsharma/fib-server
  - docker push rsharma/fib-worker



